server:
  port: 9285

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      #ddl-auto: validate
  flyway:
    baseline-on-migrate: true
    baseline-version: 1_0_1
    schemas: public
    create-schemas: true
    default-schema: public